### PR TITLE
Comment Added

### PR DESCRIPTION
**Pull request by Aayam555**
I will be writing comments in these examples in the future.
For now I wrote comment for 1 file

So, Please put this in the project

### CODE REVIEW

**Comment by triptych** [comment]
Not a fan of so much inline comments. Seems like it would be better to include a readme, or post a walkthrough with the comments instead of including so much in the source.

**Comment by triptych** [comment]
I recommend closing this as "wont fix" .

**Comment by slmjkdbtl** [comment]
Yeah sorry I think these comments are a bit messy, I'm planning to add better comments to all examples myself, I'll keep open for now as a reminder until that's finished

**Comment by slmjkdbtl** [comment]
Added comments to audio example: 44737bf

**Pull request closed without merging**
