### PR TITLE
Revert "enterState check fail fix"

### PR DESCRIPTION
**Pull request by micheg**
Reverts replit/kaboom#408

### CODE REVIEW

**Comment by micheg** [comment]
Sorry reverted

**Comment by slmjkdbtl** [comment]
A bit confused, why are we reverting this?

**Comment by micheg** [comment]
Forgive me, it's just that I'm used to svn which has been working on it for years and years, I got a bit confused with git. I wanted to reopen the bug report that I closed before the merge.

**Comment by slmjkdbtl** [comment]
Gotcha, no worry, your commit is merged correctly now 👍

**Pull request closed without merging**
