### PR TITLE
Change font size in rpg demo

### PR DESCRIPTION
**Pull request by lajbel**
The text looked very big and is not understood (and that my monitor is 1920 x 1080)

### CODE REVIEW

**Comment by slmjkdbtl** [comment]
Can you get a screenshot? It's not visible on my machine for size 9 🤔 . Maybe screen pixel density difference?

**Comment by slmjkdbtl** [comment]
Also I might change the default font to pixel font, I think the current default one it's a bit too stylized

**Comment by lajbel** [comment]
image
With the default size

**Comment by lajbel** [comment]
image
With 9 size

**Pull request closed without merging**
