### PR TITLE
Include key when calling keypress callback functions.

### PR DESCRIPTION
**Pull request by charlestudor**
Hi! Brilliant library, it's lots of fun to make stuff with!

I noticed if you add the pressed key as an argument to the callback functions it allows for some powerful functionality like the ability to make quick input/dialog prompts to the user such as "Enter your name...".

Example code:
```
keyPress([ASCII_CHARS], (key) => {
    if (gameState.promptOpen) {
      promptInput(key);
    }
  });
```

Perhaps there is already an easy way to do this though that I just missed!

Many Thanks!

### CODE REVIEW

**Comment by slmjkdbtl** [comment]
There's actually a function called `charInput` which is used in this example here https://kaboomjs.com/examples#text, but just realized it's not documented yet, sorry. But yeah it does make more sense to pass the keys.

**Comment by charlestudor** [comment]
Ah so there is! No worries, keep up the great work! 👍

**Comment by slmjkdbtl** [comment]
FYI: Just realized I forgot about this and actually removed this in `v0.5.0` for some reason. I'll add it back later!

**Comment by slmjkdbtl** [comment]
but your example looks like character input, there's a dedicated
```
charInput((ch) => {
	input.text += ch;
});
```
now

**Pull request merged**
