### PR TITLE
Added support for arrays in uniforms.

### PR DESCRIPTION
**Pull request by tristanperrow**
Arrays for shader uniforms. Soon to support struct like objects to be sent as a uniform. For example, Light a = { vec2 position, vec3 color } will be sent as a uniform such that if your shader has the struct Light, it will be able to accept that uniform to link specific variables together.

### CODE REVIEW

**Comment by lajbel** [comment]
It looks good for me, @slmjkdbtl check it!

**Review by lajbel — APPROVED** [review]

**Comment by slmjkdbtl** [comment]
Thanks, this is good! Might also want to add to the `UniformValue` type [here](https://github.com/replit/kaboom/blob/f27b2220d3977820a32e541e502127bb6dd4adc2/src/types.ts#L4817)

**Comment by tristanperrow** [comment]
Should be good? I don't think I'm missing something, but lmk!

**Comment by slmjkdbtl** [comment]
Thank you, this is great!

**Pull request merged**
